### ISSUE TITLE
Run pickup auto-sell/store feature.

### ISSUE THREAD

**Issue by Gummar** [Sumwunn/DoomRPG#1]
Hello, I have played your version of DoomRPG, I liked most of the changes you did, but I have a problem with one of your changes, I have noticed you removed run pickup auto-sell/store features on [Commit ab57ad9ba5fc2efe19a210033c8fde9ddcfe36f2](https://github.com/Sumwunn/DoomRPG/commit/ab57ad9ba5fc2efe19a210033c8fde9ddcfe36f2). I actually like the feature, because with this feature, you don't need to manually search for the items you don't want on the shop menu, which can take a lot of time if you are getting many different armors or weapons on a low amount of time, I know I can enable auto-sell on each item I don't need/don't want, but there are items I don't know about and I want to try, if I pick up an item to try and feel like I don't need it, I have to repeat the same steps every time I decide to sell an item (the one I already had or the new item) when inventory is full. I don't know if you are planning to recreate the feature in a way it doesn't use the run key or if you didn't know if it actually was useful, just going to request you to add it back. If possible, show the sell price of the item before auto-selling non-common items and show the sell prices and sprites of the items of the same category carried by the player in the HUD for comparison, then decide to sell it with the key used to auto-sell or the open shop key.

**Comment by Sumwunn** [comment]
I originally removed it because it was quite demanding for such a small
feature and when I first started working on the mod I was fighting for
stability. And I just forgot about it.

However, since ZScript exists it looks like I might be able to implement a
much cleaner version of that feature. I will look into this for sure. :)

**Comment by Gummar** [comment]
Thanks for adding it back.

**Comment by Sumwunn** [comment]
You're welcome.

I'm not sure I'll be able to implement the last you thing you talked about without hijacking every item def itself but I'm still learning the engine so maybe it's possible.
