### ISSUE TITLE
Beserk skill dosent give full health as advertised

### ISSUE THREAD

**Issue by Elkinda** [Sumwunn/DoomRPG#10]
As the title reads. By the way thanks for making this super superior version of DoomRPG!

**Comment by Sumwunn** [comment]
Thanks for the bug report! I have fixed it locally and will close this issue when I push it.

Also I forgot to update Links.txt when I started using a later GDCC version. Here's the version that should be used: 
https://www.dropbox.com/sh/e4msp35vxp61ztg/AACxlL_tuGAc1sEcR5MHS1Yoa/gdcc/gdcc-0.14.2-1-win64.7z?dl=0

**Comment by Sumwunn** [comment]
Fixed in: https://github.com/Sumwunn/DoomRPG/commit/46677abc26e36f79ee5cc0fb824a3baaab97a745
