### ISSUE TITLE
Bullet Turret 0.3 FPS

### ISSUE THREAD

**Issue by Shanjaq** [Sumwunn/DoomRPG#102]
Installing the Bullet Module on the Turret and deploying drops framerate to extreme lows when enemies are near after alert sound plays.  Framerate restores when unsummoning the Bullet Turret.

Entire Command-Line::
`"d:\games\zdoom_4_11_3\DoomRPG-ports\GZDooM 4.10.0\gzdoom.exe" -iwad ..\..\DoomRPG-wads\doom2.wad -file ..\..\DoomRPG-mods\Lexicon-beta-build-137.pk3 ..\..\DoomRPG-mods\Lexicon-miscdata-beta-build-137.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5_Brightmaps.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Beta_7.3.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Brightmaps.pk3 ..\..\DoomRPG-mods\DRLAX_1.1c.pk3 "..\..\DoomRPG-mods\DoomRL Option - Kinsie Fluff.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Metaprops.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Sounds.pk3" "..\..\DoomRPG-mods\DoomRL Option - Sounds 2016.pk3" "..\..\DoomRPG-mods\Others - Flashlights.pk3" "..\..\DoomRPG-mods\Others - Precise Crosshair 1.4.1.pk3" "..\..\DoomRPG-mods\Others - Target Spy 2.01.pk3" "..\..\DoomRPG-mods\Others - Gearbox 0.7.0.pk3" ..\..\DoomRPG-mods\BStain.wad ..\..\DoomRPG-mods\corruptioncards-v5.2.pk3 ..\..\DoomRPG-core\DoomRPG ..\..\DoomRPG-core\DoomRPG-Brightmaps ..\..\DoomRPG-core\DoomRPG-Lexicon ..\..\DoomRPG-core\DoomRPG-RLArsenal ..\..\DoomRPG-core\DoomRPG-RLMonsters ..\..\DoomRPG-core\DoomRPG-RLArsenal-Extended `

**Comment by Sumwunn** [comment]
Yeah, I noticed this. Probably just some DECORATE that needs tweaking.

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.
