### ISSUE TITLE
New CC 6.2 patch gives VM abort

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#106]
![image](https://github.com/user-attachments/assets/8a948404-ed53-422f-be32-93f366de0a22)

`"./gzdoom.exe" -config "../../cvar inis/DoomRPG.ini" -iwad "../../IWADs/Doom2.wad" -file "../../Universal mods/Mutators/corruptioncards-v6.2.pk3" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-Brightmaps" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-CorruptionCards" -stdout`

Used GZDoom 4.10.1 (also tried with latest VKDoom and GZDoom), newly downloaded CC 6.2 (I think Cutmanmike released a small patch at some point without incrementing the version number as a hotfix so hopefully that's not the cause), and latest versions of rebalance dev with the 6.2 patch (no overwrite, installed from scratch). (I know the branch name is wrong on the DRPG folder but I don't wanna mess with my DoomRunner load order lol so I just deleted the folders inside it and extracted there)

**Comment by Sumwunn** [comment]
Replace the contents of main.zscript with the pastebin and see if that fixes it (added null checks).

https://pastebin.com/LjbfctuA

**Comment by Someone65** [comment]
Crashes with line 791 instead.

**Comment by Sumwunn** [comment]
Alright, this should fix it:

https://pastebin.com/12kDpNa9

**Comment by Someone65** [comment]
Yay! Fixed. Thanks.
