### ISSUE TITLE
Character saving and equipped armors

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#14]
When saving the char, if you didn't removed your armor and boots then picked them back up you lose them forever.

**Comment by Sumwunn** [comment]
The saving is meant for exiting the game afterwards and loading up another map pack and then loading it back up. Also the reason I placed a confirmation before letting you doing so, I should update that text to be more clear.

When you save everything gets transferred into the locker (immersion!).

Does this clear things up?

**Comment by Demiosis** [comment]
Yhea thats also how im using it , when im done with one mega wad I save my char and load it up on the next

I always used the locker after rank 1 since you can't use it before, and like i said, I lose my equipped armor and boost but not the one that would be in my inventory, the one in my inventory get transferred in the locker but not the ones im curently equipped with even if they dissapear after the save happened.

**Comment by Sumwunn** [comment]
I can't find anyway to auto-unequip the players armour and boots before hand sadly.
I'll add a reminder before the player saves.
