### ISSUE TITLE
Updated with the new experimental does not see the new loot menu

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#19]
Looked at MENUDEF.txt the new menu should be between Game Difficulty and Map Events but i do not find anything new when in the game.

**Comment by Sumwunn** [comment]
I tested with GZDoom v3.2.5 and v3.7.2 and the menu appears in both.

I checked my commit and it's indeed [there](https://github.com/Sumwunn/DoomRPG/blob/experimental/DoomRPG/MENUDEF.txt#L668).

I dunno, try re-downloading.

**Comment by Demiosis** [comment]
Seem's its Elkinda's rebalance pack that was messing with it now it work fine , ill have to inform him about that and thx a lot for all the time you put in there! Keeping one the best doom Mod ever made alive and kicking is a great cause indeed!

**Comment by Sumwunn** [comment]
Elkinda's rebalance pack? What's that? That name rings a bell, can't put my finger on it.

Also your welcome, this is my favourite mod, pretty much the only one I play (HXRTC is my second fav).
