### ISSUE TITLE
Monsters become invincible with Defense stat over ~1120

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#23]
After messing around with the monster stat cap, I've realized that monsters with a defense stat well over the default 1000 cap cannot be hurt at all, becoming unkillable except through cheats. Perhaps there should be a cap to how much damage protection percent monsters can have, much like players do?

**Comment by Forevener** [comment]
Thanks for the report! Yes, I've looked at the code and found that APROP_DamageFactor becomes negative at Defense higher than 1111.
I decided to use different formula for Defense over 1000. Experimental branch is updated.

**Comment by 7824x** [comment]
> 
> 
> After messing around with the monster stat cap, I've realized that monsters with a defense stat well over the default 1000 cap cannot be hurt at all, becoming unkillable except through cheats. Perhaps there should be a cap to how much damage protection percent monsters can have, much like players do?

How do you compile the code for this mod anyways?  I have no idea how to do it, and the instructions aren't all too clear.

**Comment by Forevener** [comment]
> How do you compile the code for this mod anyways? I have no idea how to do it, and the instructions aren't all too clear.
You will need all the stuff listed in [Links.txt](https://github.com/Sumwunn/DoomRPG/blob/master/Utilities/Links.txt) downloaded and placed in the respective folders in Utilities. Then you run compile.bat

**Comment by 7824x** [comment]
> 
> 
> > How do you compile the code for this mod anyways? I have no idea how to do it, and the instructions aren't all too clear.
> 
> You will need all the stuff listed in [Links.txt](https://github.com/Sumwunn/DoomRPG/blob/master/Utilities/Links.txt) downloaded, unpacked and placed in the respective folders in Utilities. Then you run compile.bat

Well, after doing that, making a couple of light changes in the stats code in Stats.c, and picking up the whole DRPG folder and running it with compile.bat, the coding didn't update with the test changes I made.  Everything was installed in the Utilities Folder.

**Comment by Forevener** [comment]
> Well, after doing that, making a couple of light changes in the stats code in Stats.c, and picking up the whole DRPG folder and running it with compile.bat, the coding didn't update with the test changes I made. Everything was installed in the Utilities Folder.

Show me the output of the compile.bat please.

**Comment by 7824x** [comment]
> 
> Show me the output of the compile.bat please.

I have no idea what you mean by that.  I haven't done anything like code compiling in a very long time.  If you mean show how everything is setup in the folders, I can do that.
![setup](https://user-images.githubusercontent.com/36277900/53949511-06c35680-407f-11e9-93b2-8993d5b89b75.png)

**Comment by Forevener** [comment]
> I have no idea what you mean by that.

I mean: when you launch compile.bat it outputs some text - either in Command Prompt or PowerShell. And you should rename "Python 2.7.15" to just "Python".

**Comment by 7824x** [comment]
> 
> I mean: when you launch compile.bat it outputs some text - either in Command Prompt or PowerShell. And you should rename "Python 2.7.15" to just "Python", "gdcc-0.15.0-1-win64" to just "gdcc".

Utilities\astyle\bin\astyle.exe  --style=allman  --recursive  DoomRPG/scripts/*.c,*.h
Utilities\python\python.exe compile.py 
del IR\*.obj

This is what I have.  I did rename them and I just tried to run the compile.bat file, and I ended up with this in particular.

Starting a new clean compile
Compiling C libraries...FAIL
ERROR: Program quit with error code 1
There were errors. Please review the messages above.
Press any key to continue . . .

So, prior to that, the compile.bat, would just open, display text that was too fast to read, and would just close.  Now, it just stays open at least.

**Comment by Forevener** [comment]
> So, prior to that, the compile.bat, would just open, display text that was too fast to read, and would just close. Now, it just stays open at least.

If you have Discord installed, you could find me there and discuss that matter more thoroughly.
