### ISSUE TITLE
Drla Nightmare cyberdemon crash with doom rpg

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#24]
Latest Drla files (DoomRL_Arsenal_1.1.pk3+DoomRL_Monsters_Beta_7.0.pk3) with Latest Drla drpg branch (Gzdoom Version:3.7.2.0) . When a Nightmare cyberdemon target you it freeze the game without the *your game has crashed window* need to do alt+tab to cycle out of it then it pop of the window: Gzdoom is not responding.. do you wanna close the program or wait for it to respond

**Comment by Sumwunn** [comment]
Tried reproducing this with no luck on MAP 20 under hell difficulty where the cyberdemon & mastermind are both nightmare. Tried tweaking a lot of DRPG settings to no avail.
Please give me your mod list including the map wad.

Here's some things to try:

Does this happen with DRLA by itself?
Does this happen with old DRLA?
Try GZDoom v3.6.0.

There is no specific code for any monster in DRPG so it sounds like a GZDoom bug w/ new DRLA.
If you get a freeze again without DRPG, make a bug report on the ZDoom forums.

**Comment by Demiosis** [comment]
The mod list:

"GZDOOM.exe" -file "ghetto.wad" "DoomRL_Arsenal_1.1.pk3" "DoomRL_Monsters_Beta_7.0.pk3" "doomrl_arsenal_hud_1.05.wad" "DoomRPG.zip" "DoomRPG-RLArsenal.zip" "DoomRPG-RLMonsters.zip" "Doomrpg-BrightMaps.zip"

bear in mind that ghetto.wad is an oblige generated map (random map generator)

Other stats I can give you : Equipped Gear: Nano ablative armor + grappling plasteel boots shield: Cooled core , bullet barrety , cyberdyne core and Cu-acessory 

Seem to happen only when it  try to shoot his big laser beam , :The reason i can determine this is because every other attacks were executed but not this one.. 

Im gonna try drla by itself.

Never happened with old drla.

And im gonna try Gzdoom 3.6.0
