### ISSUE TITLE
GZDoom version required is wrong and the stim injector is missing from the new outpost.

### ISSUE THREAD

**Issue by MystiaLorelei** [Sumwunn/DoomRPG#25]
First off, you're using the zscript function IsPointInMap, which was added in version 3.7.0 and thus means this only runs on that or builds later then that. Tested this on a 3.7.2 install just fine, it errored out on a 3.4.1 install I use for multiplayer and development for my own projects.

Also, I'm.. not super clear exactly what older version of DRPG I was previously running since there was another attempt at reviving this once upon a time, but there was an injection computer roughly [here](https://cdn.discordapp.com/attachments/215683031241850881/555224622954446870/Screenshot_Doom_20190312_202509.png) that [existed](https://cdn.discordapp.com/attachments/215683031241850881/555224748297289768/Screenshot_Doom_20190312_202433.png) in the old version I was running. Let you [inject stims](https://cdn.discordapp.com/attachments/215683031241850881/555224750457225223/Screenshot_Doom_20190312_202438.png) without the toxin hit but cost credits.  Did this get pulled as a feature consciously or was this something another maintainer added after the official versions ended? (or did it just get left out of the new Outpost layout accidentally?)

**Comment by worldendDominator** [comment]
The injector was removed long, long ago.

**Comment by Sumwunn** [comment]
Yeah Kyle removed it ages ago because it was way too OP.
https://github.com/Kyle873/DoomRPG/commit/062b690cc15139b52458114f3a40cf7bde4edda2
https://github.com/Kyle873/DoomRPG/commit/d16bfeb22dff35cdad65d687c9bf0f2d83ab8e13

Bumped ZS version requirement to v3.7.0.
