### ISSUE TITLE
First switch in doom.wad E1M8 replaced by black, unusable wall

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#26]
The starting room in E1M8 from doom.wad has the player facing a switch that, when pressed, lowers that sector and reveals the octagonal room with Pinkies and barrels on it. For some reason, however, when I got to the level, that entire wall was instead replaced by a black, textureless wall that cannot be activated, thus rendering the player unable to proceed except through noclip.

I accidentally discovered that the DoomRPG-Doom1 folder was the culprit behind this bug, and loading DRPG without it fixes the wall.

**Comment by Sumwunn** [comment]
Ooopsie daisy. Those xlat entries were there for way too long.

Resolved in https://github.com/Sumwunn/DoomRPG/commit/7b32707a0977317d4a4bee18c6f6129ee01e493f

I'll have these changes merged into master later today.
