### ISSUE TITLE
Monster levels aren't affected by map levels over 100

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#27]
A map level is factored into monster levels in that specific map by default. If the map level goes over 100, monster levels will keep using 100 as the map level variable no matter what, and so they stop scaling up past that point.

The fastest way to verify this bug is by starting a playthrough with the drpg_monster_mapweight (not to be confused with drpg_monster_map_weight) set to a really high value (e.g. 500) on Map01, and then going to the Outpost. You will see that the monster levels listed in the transporter (which are correctly calculated) don’t match up with the monster levels actually present in the map (which will be much lower). drpg_monster_map_weight needs to be high enough to see noticeable differences, anywhere between 1.0 and 10.0 is fine.

**Comment by Sumwunn** [comment]
Map level over 100? Are you playing on a hub wad of sorts? Do you mind sharing it?

**Comment by Forevener** [comment]
I would like to see that WAD too.

**Comment by KuromeKT** [comment]
You misunderstand. I'm not talking about a literal "MAP100+" in any one wad, I'm talking about maps that have an assigned "map level" of over 100.

For example, let's say I want to do a single playthrough through all IWADs (Ultimate Doom, Doom II, TNT and Plutonia). The total map count is 122 (DRPG does not factor in secret maps). Disregarding the easy answer in WadSmoosh, what I would do is start with Ultimate Doom on drpg_monster_mapweight (aka "Starting map weight" in the Game Difficulty menu) set to 1 since it's the starting point of it all. After I finish that, I save my character, load up Doom 2, change drpg_monster_mapweight to 33 (because Ultimate Doom's E4M8 = map level 32), start a new game and then load my character. On TNT, I would change that variable to 63 (D2 MAP30 = map level 62), and lastly for Plutonia, I would change it to 93. All of that for the sake of making it so each WAD is a direct continuation of the previous as far as map levels are concerned, because map levels factor into monster levels and by doing this, you have a perfectly linear progression for monster levels.

I mentioned the IWADs just as an example, but you could theoretically design a playthrough that's virtually as long as you wish it to be, and with any one series of WADs you'd like. My point is that DRPG has a "map level" variable that is completely independent from a given WAD's actual map id (MAP##). That variable is controlled through drpg_monster_mapweight which determines what map level the playthrough will be started with. Again, it should not be confused with drpg_monster_map_weight, because "mapweight" controls the starting map level while "map_weight" controls how much this map level affects monster levels. Lastly, by default, once you clear a map, DRPG automatically increases the map level for the next map by increments of 1.

In the Outpost, you can clearly see any map's map level on the transporter. The two attached pictures showcase this. The first one shows E4M6's map level on a default playthrough of drpg_monster_mapweight set to 1, which is 30. The second one is E4M1's map level when drpg_monster_mapweight is set to 501. Notice how, in the latter case, the monster levels listed under Area Status are extremely high because of the map level also being so high.

![Screenshot_Doom_20190315_035646](https://user-images.githubusercontent.com/20332433/54414581-66051480-46d8-11e9-8791-57d1892ad517.png)
![Screenshot_Doom_20190315_035732](https://user-images.githubusercontent.com/20332433/54414582-66051480-46d8-11e9-9cb7-8eafeb2c2948.png)

So far, this is intended behaviour, but the bug reveals itself once you actually step into E4M1 in this scenario -- monsters SHOULD have levels 4008 - 6011 as listed in the transport, but instead you get monsters with levels in the 800 - 1200 range. This occurs because the calculation for monster levels caps the map level value at 100 for some reason. I strongly believe this to be a bug because DRPG can still calculate map loot just fine. Try running a map at drpg_monster_mapweight 100 and then that same map at drpg_monster_mapweight 1000 and you'll notice a BIG difference in how many crates/credits/other loot are scattered around the map, which proves that the map level isn't capped for loot calculations.

**Comment by Forevener** [comment]
I have found the limiter and removed it.
