### ISSUE TITLE
DoomRLA 1.1.1 compatability

### ISSUE THREAD

**Issue by BoneofMalkav** [Sumwunn/DoomRPG#29]
Says on the README.md that DoomRLA 1.1.1 and DoomRL Monsters 7.1 is supported but when launched I get this script warning 

> Script warning, ":textures.txt" line 16:
Unknown patch 'MA75X0' in texture 'MA75Y0'
 Script warning, ":textures.txt" line 23:
Unknown patch 'WSTEX0' in texture 'WSTEY0'
ANIMDEFS: Can't find PMARA1
Execution could not continue.
Script error, ":animdefs.txt" line 7:
Unknown texture PMARA1

Using GZDoom 3.7.2 64bit (Modern) and using Doom RPG SE Launcher 0.9.9.0

Should note that DoomRPG itself runs fine. Even with Extras.

**Comment by Sumwunn** [comment]
You have DRLA ticked in the WAD/PK3 window yeah?
https://github.com/Sumwunn/DoomRPG/wiki/FAQ#i-get-an-error-about-an-unknown-sprite-pmara1

You need to have both the patches and DRLA pk3s ticked as well.

**Comment by BoneofMalkav** [comment]
On Launcher 0.9.9.0 yeah I did try that and it didin't work. But works fine with 0.9.8.1

**Comment by Sumwunn** [comment]
Huh, I'll bug the launcher guy about it.

I'd recommend using a batch file for the meantime.
Or Doom Explorer, I'm using that myself for DRPG.

**Comment by Sumwunn** [comment]
Tested both v0.9.8.1 & v0.9.9.0 and they work fine for me.

Try deleting the launcher's config.
