### ISSUE TITLE
Curse (and possibly other status effects) displayed wrong on the HUD sometimes

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#30]
Not too sure what causes this (perhaps an overflow of some kind?), but if the player hits a curse-inducing enemy many times in quick succession (with a minigun or similar), sometimes the status effect displayed on the HUD turns into "CURSE POWERMOD" instead of "CURSE I" through "CURSE V". I believe I've seen this occur with one or two other different status effects as well. Not sure what effects this "POWERMOD" has on the status effects in question either.

**Comment by Forevener** [comment]
Try the new version, please, and let me know if problem persists.

**Comment by KuromeKT** [comment]
Very sorry for the late update. The bug has indeed been fixed, thanks!
