### ISSUE TITLE
Damage reduction augmentation values not accurate

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#33]
My character has a Defense stat of 50 (33.32% damage reduction), and I just applied the Dermal Armor augmentation at level 1. It should increase my defense by 5%, and in fact, it used to that before, but now it increased my damage reduction from 33.32% to 36.66% (a 3.34% increase), which is not consistent with the values advertised in the augmentation.

**Comment by Sumwunn** [comment]
The updated Aug Defense was calculating 5% correctly but for whatever reason the UI was not reflecting this.

So I reverted back to the original defense formula which skews along with the defense amount. Which displays correctly on the UI.

https://github.com/Sumwunn/DoomRPG/commit/df7af0ddeeff1256fcfc44f669b1e6cb1ae74f14
