### ISSUE TITLE
Unmaker from DRLA secondary fire not working as intended

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#35]
First thing first, tested with Drla alone and it work as intended , it cost 5 hp per shot. (used dumpclasses inventory command in the console then spawned in the unmaker and 3 demonic artifacts with the give command)

So the thing with this gun is that you can use right click to drain away hp instead of cells which actualy does fire BUT does not take life from your char therefore making this weapon a infinite triple death ray that clear anything but the BOSS missions cyber/mastermind/vile variant ^^'''

Warning: Lot of demons were cheezed during this bug report!

**Comment by FoxMcloud5655** [comment]
Can confirm that this happens with me and my 2 brothers as well.

**Comment by Sumwunn** [comment]
I fixed what I could on DRPG's side but it also required a change on DRLA's side which Yholl will include with the next DRLA update.

In the meantime you can apply the fix to DRLA manually, details in the commit below.
https://github.com/Sumwunn/DoomRPG/commit/51008065a735a9d9102d50666a4e71514d2d4276

I'll keep this issue open until the next DRLA update comes out.

**Comment by Sumwunn** [comment]
Fully fixed as of DRLA 1.1.2.
