### ISSUE TITLE
Suggestion: Disable Hellstorm elemental and nuke barrels when running Drla

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#37]
Either a switch of a full disable , I mean why do you play with stats if a mob or a rarely spawned barrel (a friggin BARREL of all things) can 1 shot you?  These addition make the gameplay feel really cheap at times and aren't really well designed to start with either imo... ^^'

(a REGULAR example I have in mind is doing a reinforcement mission and fight around a bit then you get 1 shot blindsided cauz a hellstorm spawned 1 quarter inches behind you and you weren'T looking in that direction for 2 secs..)

**Comment by Sumwunn** [comment]
Newest DRLA allows you to switch off the nuke barrels.

For the elemental I don't think DRPG can control that. Your best bet is to customise (I mean modify) drla's monster pk3 itself.

Or alternatively run Colourful Hell. I find it's a bit more balanced since not every enemy drops a weapon.
