### ISSUE TITLE
Natural Stat Leveling - Regen XP Decreases When 2x EP Aug Enabled

### ISSUE THREAD

**Issue by FoxMcloud5655** [Sumwunn/DoomRPG#40]
Your Regen XP from Natural Stat Leveling goes down when you have more than your standard max EP stored, such as when your PSI Projector augment is enabled.

The problem lies within line 487 of Stats.c:
```c
Player.EPMax > 0 ? ((fixed)Player.EP / Player.EPMax) : 0
```
This should include a check if your current EP is more than your max (as an easy fix), such as the following:
```c
Player.EP < Player.EPMax && Player.EPMax > 0 ? ((fixed)Player.EP / Player.EPMax) : 0
```

**Comment by Sumwunn** [comment]
Tested it and seems to do the job.

I'll include this in tomorrows commit, thanks!

**Comment by FoxMcloud5655** [comment]
No problem!  Looking forward to a new build.

**Comment by Sumwunn** [comment]
Fix included in https://github.com/Sumwunn/DoomRPG/commit/bf61ace7c940fe1fb7fd628ec3dd6a42b5069f38.
