### ISSUE TITLE
Monsters don't drop loot when killed right after spawning or strength-aura teleporting

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#41]
Monsters who are killed right after they are spawned (by an Icon of Sin spawn cube, for example) or right after they teleport behind you with a strength aura will give you XP as normal, but will drop no loot at all. This is true for any kind of monster, including Cyberdemons and such.

The easiest way to invoke this bug is to go to Doom2.wad MAP30, and kill monsters (the natural way) as soon as they are spawned.

**Comment by Sumwunn** [comment]
MonsterInit() has to wait for about 5 tics to make sure any changes to the monster has been made (stats/replacements). So naturally there will be some brief lag with initialisation.
