### ISSUE TITLE
Thermonuclear event does not spawn the bomb

### ISSUE THREAD

**Issue by Zapoopa** [Sumwunn/DoomRPG#42]
Probably i missed something, but somehow, thermonuclear event can't start. The hud shows as normal, but time is frozen and nothing hapenning. Bomb is nowhere. No warnings or messages about problems. Seems it's just not spawning.  (i remember this problem was a long time ago in original DoomRPG, but i don't know what exactly was wrong)

Tested at 3.7.2 and 4.1.1 GZDoom. Order of launch in bat. file:
1. DoomRL Arsenal
2. DoomRL Monster pack
3. DoomRPG
4. DoomRPG - DoomRL Arsenal
5. DoomRPG - DoomRL Monster pack
6. DoomRPG - Brightmaps

**Comment by Sumwunn** [comment]
I'm having no luck reproducing this so far with DOOM 2.

Do you remember which WAD and map you were on?

Thanks.

**Comment by Zapoopa** [comment]
hmm... this happening at any map of orginal doom2.wad. Wierd. 
[img]https://i.imgur.com/BOmqswu.png[/img]
[img]https://i.imgur.com/HoQG2uO.png[/img]

Launch line:
C:/DOOM/Ports/gzdoom400/gzdoom.exe -file "C:/DOOM/wads/DoomRPG/DoomRL_Arsenal.pk3" -file "C:/DOOM/wads/DoomRPG/DoomRL_Monsters_Beta.pk3" -file "C:/DOOM/wads/DoomRPG/DoomRPG-master/DoomRPG/" -file "C:/DOOM/wads/DoomRPG/DoomRPG-master/DoomRPG-RLArsenal/" -file "C:/DOOM/wads/DoomRPG/DoomRPG-master/DoomRPG-RLMonsters/" -file "C:/DOOM/wads/DoomRPG/DoomRPG-master/DoomRPG-Brightmaps/"

**Comment by Sumwunn** [comment]
Yeah... adaptive.. I had set Adaptive's gameskill to 7, where the max DRPG can handle is 6.
But Adapative's gameskill is actually 3.

Wow I'm so sorry for that muckup.
I commited the fix.
