### ISSUE TITLE
Not enough fuel tanks for biohazard event

### ISSUE THREAD

**Issue by Zapoopa** [Sumwunn/DoomRPG#43]
Problem is simple, amount of fuel tanks for biohazard event is not enough for full clean of level. May be i missed somewhere (but sure i'm not), but even with this, it's huge pain in *back*. Could you add some more additional or droping from monsters?

**Comment by Sumwunn** [comment]
Hey I played around a bit with this and seems to be the same issue as the nuke bomb.
Didn't have any problems after the fixes.
If this still happens often for you post back here and I'll re-open the issue

**Comment by Zapoopa** [comment]
Yep, you was right. Count of fuel tanks is not enough for 7-th skill level (now adaptive level is 3-rd). Even at "nightmare" i have 1 more extra fuel tank. So, thanks.
