### ISSUE TITLE
Monster count reduction settings break if map has too many monsters

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#45]
If you have a not-amazing computer like mine, it's a given that the "Monster Population %" and "Absolute Monster Limit" settings are essential to tinker with to prevent the game from running at 3 FPS when a map has upwards of 2,000 monsters. The issue, however, is that even these settings actually break and don't work as intended if the monster count is too high -- for example, maps that have 5,000+ monsters.

When that happens, a number of other DRPG scripts break too, such as monster HP bars. This was tested in Slaughterfest 2011 MAP31.

**Comment by Sumwunn** [comment]
Fixed. I'll commit tomorrow.

This line of code required it's own Delay() as it averages 700000+ iterations with 5000+ monsters, madness!

https://github.com/Sumwunn/DoomRPG/blob/master/DoomRPG/scripts/Map.c#L422

**Comment by Sumwunn** [comment]
Fixed in https://github.com/Sumwunn/DoomRPG/commit/bf61ace7c940fe1fb7fd628ec3dd6a42b5069f38
