### ISSUE TITLE
The Berserker effect does not disappear until the end of the map

### ISSUE THREAD

**Issue by WNC12k** [Sumwunn/DoomRPG#47]
When you receive the Berserker is not reported the time of using the Berserker. Once the screen stops being red, the Berserker acts until the end of the map. This can be easily checked with the help of fists.

**Comment by FoxMcloud5655** [comment]
That's vanilla Doom.  The red you see is a damage reduction buff, while the stims stay with you until the end of the map.

**Comment by WNC12k** [comment]
Really. Never paid attention to it. now I know. thank you

"The berserk pack increases the strength of the player's punch attack tenfold, but only until the current level ends. The damage increase is powerful enough to often smash humanoids to a pulp, or even sometimes kill a demon with a single blow."

**Comment by Sumwunn** [comment]
Heh, I didn't know either. 
I started to search DRPG for a cause only to find no answer then my email pinged.

Good to know.

Thinking now though, I think the the berserk pack could be RPG-ified. Perhaps scale it's timer against the strength skill in some way.
