### ISSUE TITLE
Monsters reinforcements do not have health bars and death animations

### ISSUE THREAD

**Issue by WNC12k** [Sumwunn/DoomRPG#48]
If you take the mission to kill the monsters Reinforcements the monsters appearing in this mission do not have health bars and death animations. Because of this bug the gameplay becomes less fun. This happened after the last commits. Please pay attention.

**Comment by WNC12k** [comment]
I draw your attention - some monsters reinforcements still have a health bar

**Comment by Sumwunn** [comment]
https://github.com/Sumwunn/DoomRPG/blob/master/DoomRPG/scripts/Monsters.c#L2584

When I reworked one-monster I set the Delay in there to 1, when it actually supposed to be 4.
I'll commit later today when I've confirmed that change doesn't break one-monster.

**Comment by WNC12k** [comment]
Thanks for your support!
