### ISSUE TITLE
New DRLA Backpacks not implemented

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#52]
If the backpack does spawn, it'll spawn as an empty spot meaning that not only do you not get a specialist backpack but you get no backpack at all. Not only that but the specialist backpacks of DRLA clash with DRPG's inventory capacity system in general.

**Comment by Someone65** [comment]
Oh fuck me... delete this issue. This was partly a load order issue. On the other hand, though it would still be interesting to see implementation of DRLA's special backpacks in some form. Especially the nuclear backpack which actually affects your nuclear weapons by allowing them to regen faster.

**Comment by FoxMcloud5655** [comment]
Issues, unfortunately, cannot be outright deleted.  However, as the OP, you can close the issue yourself.

**Comment by Someone65** [comment]
They CAN be deleted by anyone with admin rights. So sumwunn does have the power to do so.

**Comment by FoxMcloud5655** [comment]
Then please show me how, as in all of my repositories that I own, I have not found any way to.

**Comment by FoxMcloud5655** [comment]
So I see.  This must be a new feature as of late, as I know I wasn't able to before.

**Comment by Sumwunn** [comment]
*poof*
