### ISSUE TITLE
Add store anywhere option

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#53]
I'd like to see a version of the shop anywhere option for storage. The reason for this would be so that I can only store items when I go back to the UAC HQ rather than being able to store items any time I want. I don't like the idea of hoarding being optimal play here so this would alleviate it.

**Comment by Sumwunn** [comment]
Hello,

I've added this option, and I'll close this issue after I've tested it a bit more. :)
You can find the addition in the experimental branch for now.

**Comment by Sumwunn** [comment]
Feature seems to work fine.

If any issues arrise from it please comment here.
