### ISSUE TITLE
buying basic shield package doesn't work

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#54]
[Here's](https://gfycat.com/AmazingFriendlyGoosefish) a gif of it occurring.

Load order: ![ZDoom Executor load order](https://i.vgy.me/vYpjq1.png)

Running on latest stable GZDoom (4.1.3 as of time of posting).

**Comment by Someone65** [comment]
Just found out that buying any shield stuff doesn't work. If you get shield parts from crates it works fine, though.

**Comment by FoxMcloud5655** [comment]
Have you tried checking the shop in the Outpost?  It's supposed to spawn on the counter no matter where you purchase it.

**Comment by Someone65** [comment]
Oh, ffs... It DOES appear in the shop. It's really strange that it works that way instead of just putting it right into your inventory, though. Why doesn't it behave that way by default?

**Comment by FoxMcloud5655** [comment]
That, I have no idea.  Maybe it's limitations, or possibly old code?
