### ISSUE TITLE
Player kills himself after starting a game (lastest build 2019-07-02)

### ISSUE THREAD

**Issue by svsq** [Sumwunn/DoomRPG#55]

**Comment by svsq** [comment]
Tried different versions of GZDoom and run only DoomRPG without any mods/patches - after starting map player has 25% hp and kills himself immediately.

**Comment by svsq** [comment]
The issue is gone after clearing drpg_* lines from gzdoom.ini that relates to old version.

**Comment by FoxMcloud5655** [comment]
It would be nice to know which lines needed to be deleted.  If I encounter this bug, I'll give it a test.
