### ISSUE TITLE
Capacity Natural Leveling appears to be broken in base DRPG/DRLA.

### ISSUE THREAD

**Issue by devilemporium** [Sumwunn/DoomRPG#56]
As the title says... only DRPG settings that have been changed are auto healing and virtual credit drops.

**Comment by FoxMcloud5655** [comment]
Working fine for me.  Are you sure you have something in your inventory to acquire XP, like a radiation shielding suit?

**Comment by devilemporium** [comment]
I didn't realize that was how capacity leveled. I thought it was based off having max ammo I'm terribly stupid
