### ISSUE TITLE
Abominant boss undefined

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#58]
When an Abominant spawns in the map, it is completely unaffected by DRPG's scripts, meaning it won't show its name, HP, level or stats when pointing at it, nor will it give XP, credits or DRPG drops upon death. Might be loosely related to #38.

Other new monsters from Beta 7 might also suffer from the same issue.

**Comment by Sumwunn** [comment]
Hello,

I've added this definition and all is working now, along with the new Spider Disastermind.
The changes reside in the experimental branch for now.

Also, I opened up an issue just for Monster Definitions, feel free to post future actor names there.

Thanks.
