### ISSUE TITLE
De-Vile can't be killed.

### ISSUE THREAD

**Issue by TimeStreamer** [Sumwunn/DoomRPG#60]
Unable to kill De-Vile once it spawns in events. Fire everything I got on them without making a dent. Using DRLA and DRLA Monsters. Don't know if I'm missing some strange mechanic to kill it or if it's really a bug related with stats.

Can you help? Thanks.

PS: Found out that issue #23 (closed and merged, I believe) refers an issue much like my own, except mine only occurs with De-Viles (maybe tech-viles too. Think it happened once with those). Also, when checking monster stats below their health bars, I don't see any value above ~100. Dunno if these can be related, thought it might help.

**Comment by Demiosis** [comment]
Also if you're playing demolitionist and is on a higher difficulty and the mob have def aura it may be impervious to explosion damage/ bounce back plasma or rocket projectiles back and some monsters have resistances and immunity to some damages types (like the cacoabyss being 100% immune to plasma damage or Bruiser brothers being 100% immune to fire.)

**Comment by TimeStreamer** [comment]
I'm sorry, only today I had the chance to verify this. Confirmed, **not an issue**. Tried a few rounds today in the arena and dispatched two De-Viles rather easily with a conqueror shotgun, by destroying the 6's runes above their heads. Dumb me for not realizing they required some specific area to be shot, when other monsters in the mod have similar mechanics, like the cacobyss, who requires the wisp to be destroyed first. Many thanks for the tip on the sixes and for the demolitionist one. Ticket closed.
