### ISSUE TITLE
Unable to remove equipped Armor or Boots

### ISSUE THREAD

**Issue by Daniel-Leontiev** [Sumwunn/DoomRPG#61]
The assigned controls to remove equipped Armor or Boots do nothing.

**Comment by FoxMcloud5655** [comment]
Are your mods loaded in the correct order?  There are scripts that can overwrite others and remove functionality if not loaded correctly.

**Comment by Daniel-Leontiev** [comment]
This is my bat file

`gzdoom.exe -skill 3 -warp 1 +sv_cheats 1 +logfile "Doom RPG.log" -file "DRLA_1.1.2.pk3" "DRLM_7.2.pk3" DoomRPG\DoomRPG DoomRPG\DoomRPG-RLArsenal DoomRPG\DoomRPG-RLMonsters DoomRPG\DoomRPG-Brightmaps DoomRPG\DoomRPG-Extras`

The game works well, all features work, except I can't remove armor or boots.

**Comment by FoxMcloud5655** [comment]
That's because DoomRPG is overriding the scripts in DoomRLA.  Change your load order to include DoomRPG before DoomRLA and DoomRLMonsters, then you'll be good.

**Comment by Daniel-Leontiev** [comment]
Thank you! It's all good now. This is my bat:

`
gzdoom.exe -skill 3 -warp 1 +sv_cheats 1 +logfile "Doom RPG.log" -file DoomRPG\DoomRPG "DRLA_1.1.2.pk3" "DRLM_7.2.pk3" DoomRPG\DoomRPG-Brightmaps DoomRPG\DoomRPG-Extras DoomRPG\DoomRPG-RLArsenal DoomRPG\DoomRPG-RLMonsters
`
