### ISSUE TITLE
Unable to collect Loot for Missions

### ISSUE THREAD

**Issue by Daniel-Leontiev** [Sumwunn/DoomRPG#63]
In older version of RPG there was random loot that can be collected, this was generated by the mod in place of Armor shards and Health vials. Currently the is not loot to be found, instead there is nothing or Blue Health vials that can be picked up, but it's not doing anything.

**Comment by WarezzK** [comment]
Same. Latest version.

**Comment by Daniel-Leontiev** [comment]
Can you let me know what is the correct load order?
This is my load order:
`gzdoom.exe +sv_cheats 1 +logfile "Doom RPG.log" -file DoomRPG\DoomRPG "DRLA\DRLA_1.1.2.pk3" "DRLA\DRLM_7.2.pk3" DoomRPG\DoomRPG-Brightmaps DoomRPG\DoomRPG-Extras DoomRPG\DoomRPG-RLArsenal DoomRPG\DoomRPG-RLMonsters`

**Comment by Daniel-Leontiev** [comment]
I think I got it!
`gzdoom.exe +sv_cheats 1 +logfile "Doom RPG.log" -file "DRLA\DRLA_1.1.2.pk3" "DRLA\DRLM_7.2.pk3" DoomRPG\DoomRPG DoomRPG\DoomRPG-Brightmaps DoomRPG\DoomRPG-Extras DoomRPG\DoomRPG-RLArsenal DoomRPG\DoomRPG-RLMonsters`

**Comment by WarezzK** [comment]
I'm using DRPG Launcher now. look at this. Have fun! This mod is big amazing:) 
![image](https://user-images.githubusercontent.com/9317317/68067179-9242d380-fd43-11e9-981c-f0cdee16d932.png)
