### ISSUE TITLE
Target Spy compatibility

### ISSUE THREAD

**Issue by WNC12k** [Sumwunn/DoomRPG#66]
Good time of day. Please add Target Spy compatibility. Below the link you can see the required code. 

https://github.com/WNC12k/DoomRPG-Rebalance/commit/6cd5ebc794e15fbf1ec65725910aba25387a0650

https://github.com/WNC12k/DoomRPG-Rebalance/blob/6cd5ebc794e15fbf1ec65725910aba25387a0650/DoomRPG/scripts/inc/Monsters.h#L66

Target spy will also be updated by the developer (m8f) for doom RPG compatibility in version 1.11 later. Post on zdoom forum:

https://forum.zdoom.org/viewtopic.php?t=60784

Thank you!

**Comment by WNC12k** [comment]
Target spy will also be updated by the developer (m8f) for doom RPG compatibility in version 1.11 later.

**Comment by mmaulwurff** [comment]
Target Spy master branch now has support for DoomRPG monster health and level
https://github.com/mmaulwurff/target-spy/archive/master.zip
(if DoomRPG contains aforementioned access scripts)

**Comment by Sumwunn** [comment]
Almost done.

Also, WNC12k, how is your rebalance coming along nowadays? Would you say it's ready?
I was able to play through BTSX E1 with it a few months ago and thought it was great honestly. No longer gibbing every enemy in the game at level 40, heh.

I'm considering merging your changes, however one thing that is stopping me is how you've ripped code/classes from DRLA for the purpose of modifying drops. That would most likely create conflicts if DRLA changes that file on their side, and is also janky.

Such a thing might be achieveable via ZScript instead, and would be much cleaner than copy pasting DRLA stuff.

**Comment by Sumwunn** [comment]
Added in https://github.com/Sumwunn/DoomRPG/commit/535c2db17e0c0e21b18b976978644d5397f6220f

Thanks guys!

**Comment by WNC12k** [comment]
I agree. I also don't like that I had to copy files from the DRLA, but unfortunately I don't yet know of any other way to change the chances of deleting the DRLA itself. If you could do that with a zscript, that would be great.

As for the Rebalance itself. To date, it looks good. I keep doing this, unfortunately there is not enough time to test it completely.

**Comment by Sumwunn** [comment]
The fact that somebody even attemped to balance this massive mod makes me happy, let alone with actual progress. I attempted to rebalance it multiple times myself but I always came back unsatisfied, perhaps I approached it from the wrong angle, or maybe I'm not good at that. It has to be pretty blatant for me to change something; like the heal skill, I'm happy with that. 
I think your rebalance is probably as good as it gets, at least as far as I am concerned.

I'll see what can be done in ZScript in the meantime.

**Comment by WNC12k** [comment]
I'll post all the files I changed for balance, if suddenly you decide to implement it (or part of it). 

Changes are easily compared to the originals (your files) with each other using Notepad++ Compare plugin.

Therefore, to see what has been changed is not so difficult.

Link:
[https://www.dropbox.com/s/3o4f71e69hl6s03/Update%201.5.rar?dl=0](url)
