### ISSUE TITLE
Request: Another Monster regen aura effect

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#68]
Could there be another effect for regen aura for monsters? I always disable it and play with X3 monster Hp instead (I mean wft full heal after 5 secs?) 

But seriously, as it stand regen aura monsters are either pointless because they don't have the hp to use it properly OR in the cases of some bosses just make them impossible because you need to deal X amount of damage in 5 secs. (Ok you could run back to the outpost but, when on hell or higher you often need to kill enemies while running away from the teleporting boss because you just CAN'T kill the boss..

Regen effect suggestion: 
Double current regen effect.
Give the doubled regen effect to friendlies around.
Give a hp bonus with doubled regen effect.

**Comment by Sumwunn** [comment]
I agree, the regen aura requires a rework of sorts.

Level 100+ bosses can be almost impossible due to this.

**Comment by Demiosis** [comment]
After reading the wiki... Regeneration
Enter their regeneration cycle much faster.
Regenerate enemies around them.

Would make sense since I still encountered bosses which regeneration was off the chart... so myhea bottom line I think its more the regeneration stats on monsters that is borked and fully heal the boss all the time...

**Comment by Demiosis** [comment]
This thread is not longer relevant since I found out that the problem reside in the stats purely so, I will close this issue!
