### ISSUE TITLE
Shop anywhere option on locker bug

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#69]
When the Shop option : Shop anywhere is on locker , when you're at the outpost and buy items money is deducted from the account but the item is not given to the player. (using latest drpg version not experimental with DoomRL_Arsenal_1.1.2.pk3 and DoomRL_Monsters_Beta_7.2.pk3)

**Comment by Sumwunn** [comment]
You checked the shop desk right?

**Comment by Demiosis** [comment]
well no, actually expected it to drop at my character's feet like before... maybe put a tooltip on the option or forbid player from shopping ANYWHERE but in front of the counter? Its not really obvious for players who never tried that option.

**Comment by Sumwunn** [comment]
I'll add a tooltip in the options and in the wiki.

**Comment by Demiosis** [comment]
Thank you , that should be perfect!

**Comment by Sumwunn** [comment]
Added a note in the options in https://github.com/Sumwunn/DoomRPG/commit/f62e866bb6d3fdd0b01e12655a0058aa3640cfe7.
