### ISSUE TITLE
Game freeze when an unknow kind of black aura boss monster activate

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#70]
Not sure 100% what caused it but its either related to the nightmare archviles rezzing creatures when on a kill mission for them or the auto save popping when one of those red jokers is around... Literally freeze the entire Gzdoom no crash either... Maybe related to : Game freezing after loading a saved game ?

Follow up: retried without the mission , still end up freezing after some minutes in a level... =/ 

Managed to get further before it freeze though this time so I feel it is indeed related to : Game freezing after loading a saved game. Was playing on hell btw...

Re-Read the other topic and will try the game with GzDoom 4.1.3 see if it would help... Welp that was quick... =/ sadly not working either..

Finally retried it again with vanilla config and saw it worked so i worked down my config until I found the culprit!!

Did even more tries... Vanilla configs froze as well so at this point since I managed to clear it once I think it freeze up when activating a specific kind of Drla monster with boss aura... which one? I dunno but im pretty sure thats the problem...

Setup: "GZDOOM.exe" -file "mymap.wad" "DoomRL_Arsenal_1.1.2.pk3" "DoomRL_Monsters_Beta_7.2.pk3" "doomrl_arsenal_hud_1.05.wad" "DoomRPG.zip" "DoomRPG-RLArsenal.zip" "DoomRPG-RLMonsters.zip" "Doomrpg-BrightMaps.zip"

**Comment by Sumwunn** [comment]
Interesting finds.

Do you mind uploading your save game? Want to see if Visual Studio will gleen anything when it freezes.

Also, I'm curious, if you don't mind attempt a playthrough with either Extras or LegenDoom and nothing else.

**Comment by Demiosis** [comment]
You'll need the wad as well i think or else the save wont work so here's a google drive link to said wad.

https://drive.google.com/open?id=1AwkEsMKYUn9NUXjUthg281s3s4-FYN96

[save20.zip](https://github.com/Sumwunn/DoomRPG/files/3822905/save20.zip)

and here is the save.

Also, no I won't do those play through primarily because legend doom is very boring and extra I dunno whats this about/ what it even do and not really interested in learning it either sorry. XD

**Comment by Sumwunn** [comment]
Hey, this is most likely related to freeze discussed in my thread, apply this fix and lemme know if the freeze goes away. Thanks.

https://forum.zdoom.org/viewtopic.php?style=12&f=19&t=63766&start=105#p1124474

**Comment by Demiosis** [comment]
WELL! 10 test runs in specially to try that , seems perfectly fine! I'll keep you updated!

**Comment by Sumwunn** [comment]
Hey, since no one else is having issues with freezes so far I'm going to assume this particular issue is fixed.

If you encounter any more freezes please post another thread along with your save game, load order, and verion stuffs.

I'll pin an issue here pointing people to the freeze fix until the next DRLA update comes out.

Cheers.
