### ISSUE TITLE
Combo XP unaffected by XP multiplier

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#77]
There are two types of XP that come with killing monsters: one which is the base XP given by a monster, and one that scales up as your combo gets higher. While the normal XP is scaled properly by the XP multipler (drpg_scalexp), the combo XP remains static no matter what.

This can be tested by setting drpg_scalexp to a really low value (like 0.02), and then MDK'ing a hundred monsters at once. Watch as the player still gets a ton of XP (and levels up several times), even when the base XP is almost non-existent. I don't recall this being an issue in earlier builds.

**Comment by Sumwunn** [comment]
I'm not sure I'm reproducing this right, but with v0.10.1 (original DRPG) and my fork BFGing a room with 40-ish monsters gets me roughly the same XP with the multiplier really low.

The Combo code itself has not changed, but the method of which detecting when a monster is damaged has. Nothing is standing out to me, though, huh. I'll continue to muck about with this until I hit some variance.

**Comment by Sumwunn** [comment]
Ok so upon further inspection the Combo XP does indeed not take any multipliers into account. I'll add a separate slider for it :D.

**Comment by Sumwunn** [comment]
Added in: https://github.com/Sumwunn/DoomRPG/commit/aaeca3d1d40980c964f5c5130c50adbb85b167f8
