### ISSUE TITLE
LegenDoom support doesn't seem to work.

### ISSUE THREAD

**Issue by Silentdarkness12** [Sumwunn/DoomRPG#8]
Running DRPG with LegenDoom support, I can't actually sell any of the legendary stuff that drops from enemies, or store it. So that's a problem. And yes, I did put DRPG-LegenDoom at the end of the load order.

**Comment by Sumwunn** [comment]
Unlike DRLA, LegenDoom does not a contain a list of weapons for DRPG to process. 
LD applies effects to weapons upon spawn. So there's no way to spawn a LD weapon with a specific effect.
This eliminates the ability to store/sell specific weapons.

https://forum.zdoom.org/viewtopic.php?f=43&t=51035&start=75#p891993
