### ISSUE TITLE
Plans to support the updated Doom RLA 1.1.4, RLA Monsters 7.3?

### ISSUE THREAD

**Issue by WNC12k** [Sumwunn/DoomRPG#81]
Any plans to update to support the Doom RLA 1.1.4, RLA Monsters 7.3?

**Comment by Sumwunn** [comment]
Done (?): https://github.com/Sumwunn/DoomRPG/commit/76cee198c0c592d64d57b49eeaaf234c8d726fde

**Comment by WNC12k** [comment]
Thank you for support!
