### ISSUE TITLE
Not a bug but anyone can tell me how to compile the DoomRPG.lib?

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#84]
Either a detailed walk-through or a link to a program or something for me to go on would be much appreciated! Im very unsure on the procedure and would love some confirmations...

**Comment by Sumwunn** [comment]
Download everything from here:
https://github.com/Sumwunn/DoomRPG/blob/master/Utilities/Links.txt

Extract it all and place their root folders inside the Utilities folder inside the DRPG root folder.

Refer to compile.bat for the correct paths:
https://github.com/Sumwunn/DoomRPG/blob/master/compile.bat

You may not be able to extract Python, so if you have to install it, remove "Utilities\python\" from compile.bat, which leaves only "python.exe compile.py."

compile.bat should function afterwards.

**Comment by Sumwunn** [comment]
GDCC's correct path:
Utilities\GDCC\something.exe

**Comment by Sumwunn** [comment]
Add me on Discord (found on ZDoom) if you require further help.
