### ISSUE TITLE
Decorate scripts error

### ISSUE THREAD

**Issue by theakish** [Sumwunn/DoomRPG#86]
I have the gzdoom version , After making the bat file for launching , gzdoom says an error who says "1 errors while parsing DECORATE script"

The error Comes from actors/marines/powersuit.txt
Someone help me pls

**Comment by FoxMcloud5655** [comment]
That doesn't seem to be DoomRPG's fault...  Going to need more info than that.

What WADs are you using?
What is the actual error from the console?
What exact version of GZDoom are you running?
What is the commands you used to launch GZDoom?

**Comment by theakish** [comment]
WAD : DOOM2 1.9
actual error of console idk bc im outsider
VERSION : im using a 32 bit version that means is probably old
COMMANDS: gzdoom.exe -file DoomRPG/DoomRPG


Yeah thats it

**Comment by FoxMcloud5655** [comment]
If you don't know the version of GZDoom, then update it and try again.

**Comment by theakish** [comment]
> If you don't know the version of GZDoom, then update it and try again.

Now here Comes the problem all last gzdoom builds are 64 bit my computer is 32 bit

**Comment by FoxMcloud5655** [comment]
Not going to question why you have such old hardware when basically every machine is 64-bit nowadays...  But try LZDoom.  It might work better for you.

**Comment by theakish** [comment]
Same error . And for 64-bit computer its a long story. I had a modern one before it somehow broken entirely and i had to use my old computer from 2008

**Comment by Sumwunn** [comment]
I know this is old, but I was able to launch the Rebalance-Sync branch of DRPG w/ DRLA on LZDoom 3.88b, which has a 32-bit version.

**Comment by theakish** [comment]
> I know this is old, but I was able to launch the Rebalance-Sync branch of DRPG w/ DRLA on LZDoom 3.88b, which has a 32-bit version.

by the time you responded , i got a new pc and dont even play doom anymore but thanks for the help anyway
