### ISSUE TITLE
Rally won't teleport imp summon

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#90]
Playing DRLA with DRLA monsters, corruption cards, champions, legendoom lite, and lexicon along with all the patches for DRPG.

Summoning an imp then using rally doesn't teleport the imp to you. It just remains where it is. Not sure if this is relevant since I haven't tried to see if this is the cause, but on the level this is happening on I picked a corruption card that affects imps but doesn't apply to the summon imp.

EDIT: Rally doesn't work on any summons at all

**Comment by FoxMcloud5655** [comment]
You do know that this is base DRPG, right?  You need to submit this issue in the rebalance fork.

**Comment by Someone65** [comment]
Lol I'm not sure how Github works in terms of branches with the issues page but this bug report is specifically for the rebalance-sync branch on Sumwunn's version. Forgot to state that. Since Sumwunn's the one who updated CC support and other stuff and is basically the current maintainer of rebalance as well as updating its technical aspects further exclusively using the rebalance-sync branch, I thought it'd be appropriate to report it here.

**Comment by Sumwunn** [comment]
Do you remember which card it was?

**Comment by Someone65** [comment]
> Do you remember which card it was?

I tested and it again doesn't matter whether a card is active or not. It just doesn't work at all no matter what summon, what map, and what cards are active.

**Comment by FoxMcloud5655** [comment]
Didn't know that WNC12k wasn't maintaining their fork anymore.

https://github.com/WNC12k/DoomRPG-Rebalance

**Comment by Someone65** [comment]
> Didn't know that WNC12k wasn't maintaining their fork anymore.
> 
> https://github.com/WNC12k/DoomRPG-Rebalance

They're burnt out. Perhaps they'll return eventually.

**Comment by Sumwunn** [comment]
Some kind of issue between Corruption Cards and Champions. I have issues with them together but not separate.

Try loading Champions before Corruption Cards and see if that helps.

**Comment by Someone65** [comment]
> Some kind of issue between Corruption Cards and Champions. I have issues with them together but not separate.
> 
> Try loading Champions before Corruption Cards and see if that helps.

You're right, Champions does actually cause it. I tested changing the load order and it made no difference, even to the point that I could load my save. Disabling Champions and the corresponding DRPG patch entirely fixes it. In fact, even if I don't load corruption cards at all and ONLY Champions, the problem shows up so it doesn't seem to be a problem between CC and champions, it's purely a champions issue.

**Comment by Sumwunn** [comment]
Hmm, interesting. 

I'm currently reworking map level saving (just last known level, no actual data; makes updating the mod a bit easier), so I'll take a look at Champions after that.

Also, I've made a Relighting patch that solves the massive fps drops with Aura's and others (just excludes problematic DRPG actors from processing). Will release that sometime soon.

**Comment by Sumwunn** [comment]
Also, that reminds me: If you're using Universal Ambience, dump CosmoAmb as it causes strange issues (teleporter effect gets pushed forward a few feet?!?).

**Comment by Someone65** [comment]
As an aside since this isn't DRPG's fault, Champions also breaks DRLAX's familiars. The Lost Soul familiar can't attack properly when Champions is loaded.

EDIT: Apparently this is also what causes your own turret to be able to shoot you and other similar friendly fire related issues from other mods.

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.
