### ISSUE TITLE
Defence Drone Launcher doesn't seem to work properly

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#91]
Running DRLA + DRLA Monsters + DRLAX + Champions + CC with the rebalance-sync branch on Adaptive difficulty.

I understand you're not comfortable with making balance and gameplay changes but this feels like more of a huge oversight and some bugs put together to create an unusable yet hard to obtain weapon. Though some of this may apply to most other weapons, it's particularly bad with this one.

First of all, your defence drones can shoot you in the back and you can shoot your defence drones (in the original Rebalance both of these also seemed to be an issue with DRPG Turrets but I haven't been able to test it again yet), instantly killing them most likely. Their health doesn't seem to scale either so enemies will also instantly kill them. You can kinda work around this by crouching at ALL TIMES but that's obviously not ideal.

Second problem is a severe damage scaling issue.
Basically as laid out by Demiosis in the original Rebalance fork's issues, DRPG's DRLA balance seems to favor high base damage weapons rather than low base damage but high volume of fire weapons due to the way damage scaling and defense scaling works. This results in the extremely low damage of the defense drones basically doing nothing more than tickling enemies from any stage in the game, whether it be late or early. It uses up an exotic weapon, 4 modpacks including a very rare one, as well as a ton of your ammo to create 1 drone only for it to deal like... 5 damage per hit when it should be dealing at least 30 or something.

As an aside, I feel like this seems to also be an issue with summons in general as they have somewhat okay health but deal so little damage relative to the scaling that they just end up becoming nothing more than useless distractions both early and late game, making it so you just favor high health rather than high damage summons. (I really hope this is just a Champions issue considering my other bug report related to it but I kinda remember my experience being like this in rebalance after you left but not on Kyle's old version)

Anyway I hope you can find a solution to at least this particular weapon and perhaps some other weapons with similarly egregious damage scaling issues like it without having to do some huge, laborious overhaul.

**Comment by Someone65** [comment]
Found another case where this issue applies. The Widowmaker's spiders literally do 0 damage (as in I don't even seem damage pop offs, they just tickle enemies) to low tier enemies. I'm starting to get the feeling that scaling doesn't apply to weapon based summons at all.

EDIT: Eventually, they started doing 3 damage each hit the next map

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.
