### ISSUE TITLE
Find secrets mission not working

### ISSUE THREAD

**Issue by Someone65** [Sumwunn/DoomRPG#92]
Playing Lexicon on Maps of Chaos, rebalance-sync branch, DRLA + Monsters + DRLAX + CC + Champions.

Not really sure what caused this or if this was happening from the start of my playthrough (as I just abandoned my secret finding missions early game) but finding secrets just doesn't increment the secret count for missions for some reason. DRPG acknowledges I found a secret but it doesn't affect the actual mission count.

**Comment by Sumwunn** [comment]
Busted level tracking with a hub present when I transitioned from ACS DynamicArrays to ZScript.

Fixed in: https://github.com/Sumwunn/DoomRPG/commit/d5775dc71e65a6d408c41a1eaa417476815a729d
