### ISSUE TITLE
RNJSUS-2 shield accessory bug

### ISSUE THREAD

**Issue by sanscriptum** [Sumwunn/DoomRPG#96]
RNJSUS-2 amp bonus might not be behaving correctly, after my short test the charge was getting depleted even without firing the shot by simply switching weapons.

**Comment by Sumwunn** [comment]
I cannot reproduce this (so far). What shield components were you using and what's your load order?

Also, were you using the turret and/or summons?

**Comment by sanscriptum** [comment]
No turret, no summon, it was on a Renegade character. You can see my load order from the previous thread, it was very similar. I had a very basic shield, I think it was a Black Mesa body (still happens with Starbright), Bullet battery and Standard capacitor.

**Comment by Someone65** [comment]
For easier reference, his load order:

> "G:\gayms\doom\DoomRPG\DoomRPG-ports\GZDooM 4.12.2\gzdoom.exe" -iwad ..\..\DoomRPG-wads\doom2.wad -file ..\..\DoomRPG-mods\doom_complete.pk3 ..\..\DoomRPG-mods\mapsofchaos-ok.wad ..\..\DoomRPG-mods\Lexicon-beta-build-137.pk3 ..\..\DoomRPG-mods\Lexicon-miscdata-beta-build-137.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5_Brightmaps.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Beta_7.3.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Brightmaps.pk3 ..\..\DoomRPG-mods\DRLAX_1.1c.pk3 "..\..\DoomRPG-mods\DoomRL Option - Kinsie Fluff.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Metaprops.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Sounds.pk3" "..\..\DoomRPG-mods\DoomRL Option - Sounds 2016.pk3" "..\..\DoomRPG-mods\Others - Flashlights.pk3" "..\..\DoomRPG-mods\Others - Precise Crosshair 1.4.1.pk3" "..\..\DoomRPG-mods\Others - Target Spy 2.01.pk3" "..\..\DoomRPG-mods\Others - Gearbox 0.7.0.pk3" ..\..\DoomRPG-mods\midi_floppydisk.pk7 ..\..\DoomRPG-mods\LegenDoomLite_4.1.pk3 ..\..\DoomRPG-mods\wartrophies-v1.11.0.pk3 ..\..\DoomRPG-mods\CorruptionCards-v5.1c.pk3 ..\..\DoomRPG-mods\lk_ucminimap.pk3 ..\..\DoomRPG-mods\graveyard-v1.1.1.pk3 ..\..\DoomRPG-mods\door_only.pk3 ..\..\DoomRPG-mods\Enable_Item_Rotations.pk3 "..\..\DoomRPG-mods\1 Universal Ambience.pk3" ..\..\DoomRPG-mods\Addon-NB001-Crosshairs.wad ..\..\DoomRPG-mods\autoautosave-v1.6.2.pk3 "..\..\DoomRPG-mods\Damage Direction Indicator.pk3" ..\..\DoomRPG-mods\UniversalWeaponSway.pk3 ..\..\DoomRPG-mods\AmmoDropper.pk3 ..\..\DoomRPG-mods\FlexiHUD300.pk3 ..\..\DoomRPG-mods\mk-crits[20220315].pk3 ..\..\DoomRPG-core\DoomRPG ..\..\DoomRPG-core\DoomRPG-Brightmaps ..\..\DoomRPG-core\DoomRPG-Lexicon ..\..\DoomRPG-core\DoomRPG-RLArsenal ..\..\DoomRPG-core\DoomRPG-RLMonsters ..\..\DoomRPG-core\DoomRPG-RLArsenal-Extended ..\..\DoomRPG-core\DoomRPG-CorruptionCards ..\..\DoomRPG-core\DoomRPG-WadSmoosh ..\..\DoomRPG-core\DoomRPG-LegenDoomLite "..\..\DoomRPG-core\DoomRL Option - Sounds Override" ..\..\DoomRPG-mods\nashgore.pk3 ..\..\DoomRPG-mods\bludtype.txt

**Comment by sanscriptum** [comment]
Also FYI it was on a master branch from [here](https://github.com/WNC12k/DoomRPG-Rebalance), so it might be fixed already?

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.
