### ISSUE TITLE
Medical Stuff Sprites

### ISSUE THREAD

**Issue by Wickez** [Sumwunn/DoomRPG#98]
Ey, yo.

What about implementing a more cohesive set of medical pickup items for the mod, instead of the current medley of various Doom engine games' sprites?

Something like these below? Also, offsets were already checked, and brightmaps included.

![Medikits](https://github.com/Sumwunn/DoomRPG/assets/50903250/386a5b44-fef9-4e9c-9b0a-127ade558a86)

This way, the mod would have its own unique set.

**Comment by FoxMcloud5655** [comment]
Interesting idea, but I feel like it works well enough already as is.  Maybe that's just because I'm used to it though.

**Comment by Someone65** [comment]
I do like the better cohesion that the ones Wickez proposes to use have.

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.

**Comment by Sumwunn** [comment]
I like these. 

You still got them?

**Comment by Wickez** [comment]
> I like these.
> 
> You still got them?

Howdie. Yes, the link: https://mega.nz/file/5wUQWD6I#ZhrNUWbGmE8djA7OeDppVJeubrybzeBMIXy5KaMgQpI

**Comment by Sumwunn** [comment]
Merged in https://github.com/Sumwunn/DoomRPG/commit/5f49a7f1aed0fdc683c55cf01248923b6da8f515.
