### ISSUE TITLE
Pandemonia issue - Evil marine

### ISSUE THREAD

**Issue by RonDallas** [Sumwunn/DoomRPG#99]
So, i use Pandemonia monsters (lvl 17, rank 3, Scout). And i got an Evil marine on reinforcements mission. And i cant kill him - he is to fast and rapidfire for that rank.

**Comment by FoxMcloud5655** [comment]
Sounds like somebody needs to invest in invulnerability.

**Comment by RonDallas** [comment]
It`s a level 3 of the wad

**Comment by FoxMcloud5655** [comment]
And you're level 17...  You should way be able to get invulnerability by that point and the energy to force cast it.

**Comment by RonDallas** [comment]
Ok, i make it by myself. But i also forgot how to compile the *lib and where is "AMOUNT_PANDM" for how much there is monsters. If no sprite issue and another bug - 2.4.1 monsterpack is ready for pull

**Comment by RonDallas** [comment]
Nah. I didn`t touch turret.c and healthbars.c
![Знімок екрана 2024-06-15 145226](https://github.com/Sumwunn/DoomRPG/assets/32035822/fc0da921-5a1c-4a81-b24e-fb1d33025cc9)

**Comment by RonDallas** [comment]
Download release ver., without my patch. Same errors.
![image](https://github.com/Sumwunn/DoomRPG/assets/32035822/39a1a624-91a5-4063-86a5-1fea09afafc3)

**Comment by Sumwunn** [comment]
I forgot to update Links.txt. Apologies.

Should compile after using the following GDCC version:

https://www.dropbox.com/scl/fo/4gwbx0gbvvcxgsuk7as0z/ACNeRqcBSZQVnW29Da6ZqIU?dl=0&e=1&preview=gdcc-git-0.16.1.34.gbd26e760-1-win64.7z&rlkey=eiqrd4tefp7br7sf2f4ibduw5

**Comment by RonDallas** [comment]
Thanks)
